BEGIN
    SET NOCOUNT ON;

    DECLARE @RegistroExistente INT;
    DECLARE @HoraAtual TIME;
    SET @HoraAtual = CAST(GETDATE() AS TIME);
	begin tran
		IF  @HoraAtual >= '05:00:00' and @HoraAtual < '12:00:00'
		BEGIN
			SELECT @RegistroExistente = COUNT(*)
			FROM MOV_PAV_FISIO
			WHERE PRONTUARIO = @COD AND CAST(DATAATUA AS DATE) = CAST(GETDATE() AS DATE);
			
				IF @RegistroExistente > 0
				begin
					update MOV_PAV_FISIO
					set FISIO_MANHA1 = @PAV1,
					FISIO_MANHA2 = @PAV2,
					FISIO_MANHA3 = @PAV3,
					FISIO_MANHA4 = @PAV4,
					FISIO_MANHA5 = @PAV5,
					FISIO_MANHA6 = @PAV6,
					FISIO_MANHA7 = @PAV7,
					FISIO_MANHA8 = @PAV8,
					USU_MANHA = @USU
					WHERE PRONTUARIO = @COD AND CAST(DATAATUA AS DATE) = CAST(GETDATE() AS DATE)
				END
				ELSE
				BEGIN
					INSERT INTO MOV_PAV_FISIO
					(PRONTUARIO, DATAATUA, FISIO_MANHA1, FISIO_MANHA2, FISIO_MANHA3, FISIO_MANHA4, 
					 FISIO_MANHA5, FISIO_MANHA6, FISIO_MANHA7, FISIO_MANHA8, USU_MANHA)
					VALUES
					(@COD, CURRENT_TIMESTAMP, @PAV1, @PAV2, @PAV3, @PAV4, 
					 @PAV5, @PAV6, @PAV7, @PAV8, @USU)
				end
			END
		IF  @HoraAtual >= '12:00:00' and @HoraAtual < '18:00:00'
		BEGIN
			SELECT @RegistroExistente = COUNT(*)
			FROM MOV_PAV_FISIO
			WHERE PRONTUARIO = @COD AND CAST(DATAATUA AS DATE) = CAST(GETDATE() AS DATE);
			
				IF @RegistroExistente > 0
				begin
					update MOV_PAV_FISIO
					set FISIO_TARDE1 = @PAV1,
					FISIO_TARDE2 = @PAV2,
					FISIO_TARDE3 = @PAV3,
					FISIO_TARDE4 = @PAV4,
					FISIO_TARDE5 = @PAV5,
					FISIO_TARDE6 = @PAV6,
					FISIO_TARDE7 = @PAV7,
					FISIO_TARDE8 = @PAV8,
					USU_MANHA = @USU
					WHERE PRONTUARIO = @COD AND CAST(DATAATUA AS DATE) = CAST(GETDATE() AS DATE)
				END
				ELSE
				BEGIN
					INSERT INTO MOV_PAV_FISIO
					(PRONTUARIO, DATAATUA, FISIO_MANHA1, FISIO_MANHA2, FISIO_MANHA3, FISIO_MANHA4, 
					 FISIO_MANHA5, FISIO_MANHA6, FISIO_MANHA7, FISIO_MANHA8, USU_MANHA)
					VALUES
					(@COD, CURRENT_TIMESTAMP, @PAV1, @PAV2, @PAV3, @PAV4, 
					 @PAV5, @PAV6, @PAV7, @PAV8, @USU)
				end
			END
